apiVersion: app/v1
kind: Deployment
metadata:
  labels:
    run: test
  name: test
spec:
  replicas: 3
  selector:
    matchLabels:
      run: test
  minReadySeconds: 5
  strategy:
    RollingUpdate:
      maxSurge: 1
      maxUnavalible: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: test
    spec:
      container:
      - image: docker pull nginx:1.23
        name: nginx-ctr
