apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc1
  container:
  - image: ubuntu:latest
    name: ubuntu-ctr
    command: ["/bin/bash", "-c"]
    args: ["sleep 60m"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - moluntPath: /data
      name: data
