apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      db: redis
  replicas: 3
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        db: redis
    spec:
      containers:
        - image: redis:7-alpine
          name: redis-ctr
