apiVersion: v1
kind: Namespace
metadata:
  name: acg-ns
---
apiVersion: v1
kind: Service
metadata:
  namespace: acg-ns
  name: acg-lb
spec:
  type: LoadBalancer
  ports: 
  - port: 80
  selector:
    app: acg-stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acg-ns
  name: acg-web
  labels:
    app: acg-stress
spec:
  selector:
    matchLabels:
      app: acg-stress
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: acg-stress
    spec:
      containers:
      - name: stresser
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: acg-hpa
  namespace: acg-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: acg-ns
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
